// Code generated by goctl. DO NOT EDIT.
package types

type GetUserRequest struct {
	UserId string `path:"user_id"`
}

type GetUserResponse struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
	Email  string `json:"email"`
}
