// Code generated by goctl. DO NOT EDIT.
// Source: group.proto

package server

import (
	"context"

	"group/internal/logic"
	"group/internal/svc"
	"group/pb/starcloud/rpc/group"
)

type GroupServiceServer struct {
	svcCtx *svc.ServiceContext
	group.UnimplementedGroupServiceServer
}

func NewGroupServiceServer(svcCtx *svc.ServiceContext) *GroupServiceServer {
	return &GroupServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *GroupServiceServer) GetUserGroup(ctx context.Context, in *group.GetUserGroupRequest) (*group.GetUserGroupResponse, error) {
	l := logic.NewGetUserGroupLogic(ctx, s.svcCtx)
	return l.GetUserGroup(in)
}
